# Generated by Django 5.0.6 on 2024-06-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationSystem', '0002_remove_customusermodel_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='direct_referrals',
            field=models.CharField(blank=True, default='', max_length=99999),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='indrect_referrals',
            field=models.CharField(blank=True, default='', max_length=99999),
        ),
    ]
