# Generated by Django 5.0.6 on 2024-06-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationSystem', '0003_customusermodel_direct_referrals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='points_earned',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
