# Generated by Django 5.0.6 on 2024-06-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationSystem', '0004_alter_customusermodel_points_earned'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='indirectReferrals',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
