# Generated by Django 5.0.6 on 2024-06-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationSystem', '0006_tokensmodel_refcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokensmodel',
            name='refCode',
            field=models.CharField(default='', max_length=240, null=True),
        ),
    ]
