# Generated by Django 5.0.6 on 2024-06-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationSystem', '0007_alter_tokensmodel_refcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='non_pro_referrals',
            field=models.CharField(blank=True, default='', max_length=99999),
        ),
    ]
