# Generated by Django 5.0.6 on 2024-06-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationSystem', '0008_customusermodel_non_pro_referrals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='points_earned',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
