# Generated by Django 5.0.6 on 2024-06-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationSystem', '0009_alter_customusermodel_points_earned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='indirectReferrals',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='points_earned',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='referral_code_expired',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='referrals',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
