# Generated by Django 5.0.6 on 2024-06-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationSystem', '0010_alter_customusermodel_indirectreferrals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='points_earned',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
