# Generated by Django 5.0.6 on 2024-06-28 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationSystem', '0011_alter_customusermodel_points_earned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customusermodel',
            old_name='indrect_referrals',
            new_name='indirect_referrals',
        ),
    ]
