# Generated by Django 5.0.6 on 2024-06-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationSystem', '0012_rename_indrect_referrals_customusermodel_indirect_referrals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='points_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
