# Generated by Django 5.0.6 on 2024-06-25 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentSystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountmodel',
            old_name='amount',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='transactionmodel',
            old_name='amount',
            new_name='balance',
        ),
    ]
