# Generated by Django 5.0.6 on 2024-06-25 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentSystem', '0002_rename_amount_accountmodel_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionmodel',
            old_name='balance',
            new_name='amount',
        ),
    ]
