# Generated by Django 5.0.6 on 2024-06-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentSystem', '0004_paymentinfomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfomodel',
            name='carrier',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentinfomodel',
            name='mobileNumber',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='paymentinfomodel',
            name='paymentMethod',
            field=models.CharField(choices=[('mobile_money', 'Mobile Money')], default='mobile_money', max_length=20),
        ),
    ]
