# Generated by Django 5.0.6 on 2024-06-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentSystem', '0007_alter_transactionmodel_carrier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfomodel',
            name='carrier',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentinfomodel',
            name='mobileNumber',
            field=models.CharField(max_length=15),
        ),
    ]
