# Generated by Django 5.0.6 on 2024-06-25 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentSystem', '0008_alter_paymentinfomodel_carrier_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentinfomodel',
            old_name='mobileNumber',
            new_name='accountNumber',
        ),
    ]
