# Generated by Django 5.0.6 on 2024-06-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentSystem', '0009_rename_mobilenumber_paymentinfomodel_accountnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentChannels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carriers', models.CharField(choices=[('mobile_money', 'Mobile Money')], max_length=20)),
            ],
        ),
    ]
