# Generated by Django 5.0.6 on 2024-06-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentSystem', '0010_paymentchannels'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentchannels',
            name='name',
            field=models.CharField(default='j', max_length=100),
        ),
    ]
