# Generated by Django 5.0.6 on 2024-06-25 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentSystem', '0013_alter_paymentchannels_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentchannels',
            old_name='carriers',
            new_name='methods',
        ),
    ]
