# Generated by Django 5.0.6 on 2024-06-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentSystem', '0014_rename_carriers_paymentchannels_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfomodel',
            name='paymentMethodName',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
