# Generated by Django 5.0.6 on 2024-06-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentSystem', '0015_paymentinfomodel_paymentmethodname'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfomodel',
            name='email',
            field=models.CharField(default='', max_length=240),
        ),
        migrations.AddField(
            model_name='paymentinfomodel',
            name='firstName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='paymentinfomodel',
            name='lastName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
